<?php

/**
 * @file
 * Contains big_red_bear.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function big_red_bear_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the big_red_bear module.
    case 'help.page.big_red_bear':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A Very Cornellian Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function big_red_bear_theme() {
  return [
    'big_red_bear' => [
      'render element' => 'children',
    ],
  ];
}
